import assert from 'node:assert/strict';
import {SCENARIO,STOPS,STOP,RESIDENTS,DEFAULT_DESIGN} from '../dist/data.js';
import {evaluate,summary,scheduleBus,busPosition,personPosition,resultFor,roadPath,validateDesign} from '../dist/engine.js';
const copy=x=>structuredClone(x);let checks=0;
function check(name,fn){fn();checks++;console.log('PASS '+name);}
const initial=evaluate(DEFAULT_DESIGN);
check('deterministic result / 12 people / initial baseline',()=>{assert.deepEqual(initial,evaluate(DEFAULT_DESIGN));assert.equal(initial.results.length,12);assert.deepEqual(summary(initial.results),{ontime:4,late:3,impossible:5,count:7,average:60});});
check('one bus must finish a round trip before next departure',()=>{const s=initial.schedules[0];assert.equal(s.cycle,58);assert.deepEqual(s.departures,[450,508,566]);assert.equal(s.visits[3].arr,476);assert.equal(s.visits[3].dep,479);assert.equal(s.visits[6].arr,505);assert.equal(s.visits[6].dep,508);});
check('Junho: walk 15 + wait 5 + bus 16 + exit 4 = 40 minutes',()=>{const r=initial.results.find(r=>r.id==='junho');assert.equal(r.arrival,470);assert.equal(r.walkIn,15);assert.equal(r.initialWait,5);assert.equal(r.inVehicle,16);assert.equal(r.walkOut,4);assert.equal(r.duration,40);assert.equal(r.rides[0].busId,1);assert.equal(r.rides[0].board,450);assert.equal(r.rides[0].alight,466);});
check('Minseo walks from hill home to reachable north bridge, catches future bus',()=>{const p=RESIDENTS[0],r=initial.results[0];assert.equal(r.origin,'N');assert.equal(r.walkIn,22);assert.equal(r.rides[0].board,469);assert.equal(r.initialWait,7);assert.equal(r.arrival,480);const pos=personPosition(p,r,initial.schedules,439);assert.ok(Math.abs(pos.point[0]-STOP.H.x)<50);});
check('missing a bus by 1 minute requires next actual visit',()=>{const d={buses:[{route:['A','S'],departure:450},{route:[],departure:420}],lowBus:0},s=evaluate(d).schedules;const p={id:'test',ready:448,deadline:600,maxWalk:10,low:false,access:{A:3},egress:{S:1}};const r=resultFor(p,d,s);assert.ok(r.rides[0].board>450);assert.equal(r.rides[0].board,504);});
check('transfer requires two full minutes, exact connection is allowed',()=>{const d={buses:[{route:['A','T'],departure:420},{route:['T','F'],departure:431}],lowBus:0};const p={id:'test',ready:420,deadline:600,maxWalk:10,low:false,access:{A:0},egress:{F:0}},r=resultFor(p,d,evaluate(d).schedules);assert.equal(r.rides.length,2);assert.equal(r.rides[0].alight,429);assert.equal(r.rides[1].board,431);const lateBus=copy(d);lateBus.buses[1].departure=430;const missed=resultFor(p,lateBus,evaluate(lateBus).schedules);assert.ok(missed.rides[1].board>430);});
check('a wheelchair user never boards the other regular bus, including transfers',()=>{const d={buses:[{route:['A','T'],departure:420},{route:['T','F'],departure:431}],lowBus:0},p={id:'test',ready:420,deadline:600,maxWalk:10,low:true,access:{A:0},egress:{F:0}},r=resultFor(p,d,evaluate(d).schedules);assert.equal(r.status,'impossible');});
check('stop addition/removal, first departure and low-floor reassignment alter outcomes',()=>{for(const fn of [d=>d.buses[0].route.push('H','M'),d=>d.buses[0].route.splice(3,1),d=>d.buses[0].departure=460,d=>d.lowBus=1]){const d=copy(DEFAULT_DESIGN);fn(d);assert.notDeepEqual(evaluate(d).results,initial.results);}});
check('adding a hill branch increases round-trip time and creates real tradeoffs',()=>{const d=copy(DEFAULT_DESIGN);d.buses[0].route=['A','T','N','H','S','M'];const e=evaluate(d);assert.ok(e.schedules[0].cycle>initial.schedules[0].cycle);assert.notEqual(e.results[2].arrival,null);assert.ok(e.results.some((r,i)=>r.arrival!=null&&initial.results[i].arrival!=null&&r.duration>initial.results[i].duration));});
check('destination exit after 10:00 counts as unreachable in the scenario',()=>{const d={buses:[{route:['A','T'],departure:590},{route:[],departure:420}],lowBus:0},p={id:'test',ready:590,deadline:600,maxWalk:5,low:false,access:{A:0},egress:{T:2}},r=resultFor(p,d,evaluate(d).schedules);assert.equal(r.status,'impossible');});
check('invalid designs cannot create a third bus or impossible departures',()=>{assert.equal(validateDesign({...DEFAULT_DESIGN,buses:[...DEFAULT_DESIGN.buses,DEFAULT_DESIGN.buses[0]]}),false);assert.equal(validateDesign({...DEFAULT_DESIGN,lowBus:2}),false);const d=copy(DEFAULT_DESIGN);d.buses[0].departure=400;assert.equal(validateDesign(d),false);});
check('all road shortest paths begin/end at the defined connected stop',()=>{for(const a of STOPS)for(const b of STOPS){if(a.id===b.id)continue;const p=roadPath(a.id,b.id);assert.deepEqual(p.points[0],[a.x,a.y]);assert.deepEqual(p.points.at(-1),[b.x,b.y]);assert.equal(p.minutes,p.edges.reduce((t,e)=>t+e.minutes,0));}});
const designs=[DEFAULT_DESIGN,{buses:[{route:['A','T','N','H','S','M'],departure:435},{route:['H','N','T','E','F'],departure:440}],lowBus:0},{buses:[{route:['H','M','F','A'],departure:452},{route:['A','S','T'],departure:428}],lowBus:1}];
check('schedule continuity, dwell, boarding, transfer and animation invariants across varied designs',()=>{for(const d of designs){const e=evaluate(d);for(const s of e.schedules){for(let i=1;i<s.segments.length;i++){const a=s.segments[i-1],b=s.segments[i];assert.ok(b.start>=a.end);assert.deepEqual(a.points.at(-1),b.points[0]);}for(const v of s.visits){const pos=busPosition(s,v.arr+.01);assert.deepEqual(pos.point,[STOP[v.stop].x,STOP[v.stop].y]);}}for(let i=0;i<RESIDENTS.length;i++){const p=RESIDENTS[i],r=e.results[i];if(r.arrival==null)continue;assert.equal(r.duration,r.walkIn+r.initialWait+r.inVehicle+r.transferWait+r.walkOut);assert.ok(r.arrival<=600);assert.equal(r.status,r.arrival<=p.deadline?'ontime':'late');assert.ok(r.rides.length<=2);for(let j=0;j<r.rides.length;j++){const ride=r.rides[j];assert.ok(ride.board>=(j?r.rides[j-1].alight+2:p.ready+r.walkIn));if(p.low)assert.equal(ride.busId,d.lowBus);assert.deepEqual(busPosition(e.schedules[ride.busId],ride.board).point,[STOP[ride.from].x,STOP[ride.from].y]);assert.deepEqual(personPosition(p,r,e.schedules,ride.board+.01).point,busPosition(e.schedules[ride.busId],ride.board+.01).point);}}}});
console.log(`${checks} meaningful engine checks passed.`);

